source 'https://github.com/CocoaPods/Specs.git'

# use_frameworks!

target 'IBDesignable', :exclusive => true do
  pod "IBDesignable", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IBDesignable", :path => "../"

  
end
